version: "3.9"
services:
  api_main:
    container_name: api_main
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
      db_main:
        condition: service_started
      redis:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.api
    entrypoint: [ "dotnet", "api.v1.main.dll" ]
    ports:
      - 6001:8080
    volumes:
      - ./api/main/logs:/logs/main
      - ./files:/files

  api_email:
    container_name: api_email
    restart: always
    depends_on:
      rabbitmq:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.api
    entrypoint: [ "dotnet", "api.v1.email.dll" ]
    ports:
      - 6002:8080

  db_main:
    container_name: db_main
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 6011:5432
    volumes:
      - ./postgres/main/data:/var/lib/postgresql/data
      - ./postgres/main/create.sql:/docker-entrypoint-initdb.d/create.sql

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 6021:8080

  redis:
    container_name: redis
    image: redis:7.2.4
    restart: always
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/root/redis
      - ./redis/redis.conf:/usr/local/ets/redis/redis.conf

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.0-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log.rabbitmq/