FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /api
COPY api/api.v1.main/*.csproj .
RUN dotnet respore
COPY api/ .
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
EXPOSE 80
ENTRYPOINT [ "dotnet" "api.v1.main.dll" ]