FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /api
COPY ../api/api.email.sln ./
COPY ../api/api.v1.email/*.csproj ./api.v1.email/
COPY ../api/helper.v1.configuration/*.csproj ./helper.v1.configuration/
COPY ../api/component.v1.email/*.csproj ./component.v1.email/
RUN dotnet restore

COPY ../api/ ./
RUN dotnet publish api.email.sln -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .

EXPOSE 80