FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /api
COPY ../api/api.proxy.sln ./
COPY ../api/api.v1.proxy/*.csproj ./api.v1.proxy/
RUN dotnet restore

COPY ../api/ ./
RUN dotnet publish api.proxy.sln -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .

EXPOSE 80